# Generated by Django 5.2 on 2026-04-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_employeeprofessionaldetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocumentmaster',
            name='document_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('resume', 'Resume'), ('offer_letter', 'Offer Letter'), ('revision_letter', 'Revision Letter'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
