# Generated by Django 5.2 on 2026-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_employee_address_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocumentmaster',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='employeedocumentmaster',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employeedocumentmaster',
            name='private_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employeedocumentmaster',
            name='public_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employeedocumentmaster',
            name='unique_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
