# Generated by Django 5.2 on 2026-05-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_add_designation_to_professional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='reporting_to',
            field=models.ForeignKey(blank=True, db_column='reporting_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='workforce.employeeprofessionaldetails'),
        ),
    ]
