# Generated by Django 5.2 on 2026-05-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_alter_employeeprofessionaldetails_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='workforce.employee'),
        ),
    ]
