# Generated by Django 5.2 on 2026-05-25 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_alter_employeeprofessionaldetails_reporting_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concern',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='concern',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='concern',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='concern',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='concern',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_concerns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concern',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='unique_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='concern',
            name='reason_category',
            field=models.CharField(choices=[('performance', 'Performance'), ('welfare', 'Welfare'), ('exit', 'Exit'), ('misconduct', 'Misconduct'), ('attendance', 'Attendance'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='concern',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_concerns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='concern',
            table='concern_request',
        ),
        migrations.CreateModel(
            name='ConcernResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True)),
                ('audio_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('document_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='workforce.concern')),
            ],
            options={
                'db_table': 'concern_response',
            },
        ),
        migrations.CreateModel(
            name='ConcernAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('concern_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='workforce.concernresponse')),
            ],
            options={
                'db_table': 'concern_access_log',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConcernAttachment',
        ),
    ]
