# Generated by Django 5.2 on 2026-05-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_alter_concern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('read', 'Read'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
