# Generated by Django 5.2 on 2026-05-26 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0011_alter_concern_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exitinterviewresponse',
            old_name='growth_opportunity',
            new_name='anything_else',
        ),
        migrations.RenameField(
            model_name='exitinterviewresponse',
            old_name='additional_comments',
            new_name='anything_else_details',
        ),
        migrations.RenameField(
            model_name='exitinterviewresponse',
            old_name='met_expectations',
            new_name='could_prevent_leaving',
        ),
        migrations.RenameField(
            model_name='exitinterviewresponse',
            old_name='custom_reason_text',
            new_name='could_prevent_leaving_details',
        ),
        migrations.RemoveField(
            model_name='exitinterviewresponse',
            name='primary_reason',
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='comm_between_departments',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='comm_managers_staff',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='comm_throughout_company',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='comm_within_department',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='coworker_relationship',
            field=models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='enjoyed_least',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='enjoyed_most',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='enjoyed_work',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='environment_rating',
            field=models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='familiar_disciplinary_procedures',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='job_importance_extent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='joined_for_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='joined_for_career',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='joined_for_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='joined_for_reputation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='joined_for_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_better_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_better_compensation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_better_designation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_better_job_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_better_working_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_commuting_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_difficult_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_family_circumstances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_illness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_lack_of_recognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_moving_out_of_town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_no_advancement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_retirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='left_self_employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='morale_rating',
            field=models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='most_important_factor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='position_met_expectations',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='position_represented_properly',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='positive_aspects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='rating_advancement',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='rating_company_benefits',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='rating_others',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='rating_overall',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='rating_salary',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='rating_working_conditions',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='satisfied_training_quality',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='sufficient_professional_dev',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='sufficient_resources',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='suggestions_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='suggestions_for_improvement',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='supervisor_relationship',
            field=models.CharField(blank=True, choices=[('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='supervisors_helpful',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='work_hours_reasonable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='workload_reasonable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
