# Generated by Django 5.2 on 2026-05-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_rename_growth_opportunity_exitinterviewresponse_anything_else_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
