# Generated by Django 5.2 on 2026-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0013_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitinterviewresponse',
            name='last_project_worked',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
