# Generated by Django 5.2 on 2026-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_exitinterviewresponse_last_project_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofessionaldetails',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetails',
            name='last_project_worked',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
