# Generated by Django 5.2 on 2026-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0018_user_designation_user_full_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
